durabilityBuilder/urls.py
from django.urls import path, include
from durabilityBuilder import views


app_name = 'durabilityBuilder'


urlpatterns = [
    path('', views.dashboard, name='durabilitybuilder_index'),
    path('home', views.dashboard, name='home'),
    path('send_confirm', views.send_confirmation, name='send_confirm'),
    path('get_started', views.get_started, name='get_started'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('under_construction/', views.under_construction, name='under_construction'),
    path('intro_day1/', views.intro_day1, name='intro_day1'),
    path('intro_day2/', views.intro_day2, name='intro_day2'),
    path('intro_day3/', views.intro_day3, name='intro_day3'),
    path('intro_day4/', views.intro_day4, name='intro_day4'),
    path('intro_day5/', views.intro_day5, name='intro_day5'),
    path('intro_day6/', views.intro_day6, name='intro_day6'),
    path('intro_day7/', views.intro_day7, name='intro_day7'),
    path('intro_day8/', views.intro_day8, name='intro_day8'),
    path('intro_day9/', views.intro_day9, name='intro_day9'),
    path('intro_day10/', views.intro_day10, name='intro_day10'),
    path('intro_day11/', views.intro_day11, name='intro_day11'),
    path('intro_day12/', views.intro_day12, name='intro_day12'),
    path('intro_day13/', views.intro_day13, name='intro_day13'),
    path('intro_day14/', views.intro_day14, name='intro_day14'),
]

durableAthlete/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("", include("durabilityBuilder.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path('admin/', admin.site.urls),
]

durabilityBuilder/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=128)


class Program(models.Model):
    description = models.CharField(max_length=128)
    duration_days = models.IntegerField(default=0)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    display_order = models.IntegerField(default=1)
    active = models.BooleanField(default=True)

durabilityBuilder/forms.py
from django import forms
from .models import Program


class ContactForm(forms.Form):
    name = forms.CharField(required=True,
                           label="Name",
                           error_messages={"required": "Please enter your name"})
    email = forms.CharField(required=True,
                            label="Email",
                            error_messages={"required": "Please enter your Email Address"})
    subject = forms.CharField(required=True,
                              label="Subject",
                              error_messages={"required": "Please enter a subject"})
    message = forms.CharField(widget=forms.Textarea,
                              label="Message",
                              error_messages={"required": "Please enter a message"})


class ProgramChoice(forms.Form):
    choices = Program.objects.filter(active=True).order_by('display_order').values_list('id', 'description')
    account_choices = (
        ("a1", "I need to create my Durability Builder account"),
        ("a2", "I have a Durability Builder account"),
    )
    program = forms.ChoiceField(label='',
                                choices=choices)

    account = forms.ChoiceField(label='',
                                choices=account_choices,
                                widget=forms.RadioSelect(attrs={'class': "program_select_item"}))

durabilityBuilder/views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render, redirect
from .forms import ContactForm, ProgramChoice
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseRedirect


def durabilitybuilder_index(request):
    if request.method == "GET":
        form = ContactForm()
    else:
        form = ContactForm(request.POST)
        if form.is_valid():
            body = {
                "name": "Name: " + form.cleaned_data["name"],
                "email": "Email Address: " + form.cleaned_data["email"],
                "subject": "Subject: " + form.cleaned_data["subject"],
                "message": "Message: " + form.cleaned_data["message"],
            }
            message = "\n".join(body.values())
            try:
                send_mail("Message From Durability Builder Website",
                          message,
                          "mike@durabilitybuilder.com",
                          ["mikeschmitz42@gmail.com", "Tim@MultisportEnduranceAcademy.com"])
            except BadHeaderError:
                return HttpResponse("Invalid Header Found")

            return redirect("durabilityBuilder:send_confirm")

    return render(request, 'durabilityBuilder/index.html', {"form": form})


def under_construction(request):

    return render(request, 'durabilityBuilder/under_construction.html')


def send_confirmation(request):

    return render(request, 'durabilityBuilder/send_confirmation.html')


def get_started(request):
    if request.method == "GET":
        form = ProgramChoice()
    else:
        form = ProgramChoice(request.POST)
        if form.is_valid():
            program_choice = form.cleaned_data["program"]
            account = form.cleaned_data["account"]

            request.session["program_choice"] = program_choice

            if account == "a1":
                return redirect("durabilityBuilder:under_construction")
            else:
                return redirect("durabilityBuilder:dashboard")

        else:
            return HttpResponse("Invalid Form Value(s)")

    return render(request, 'durabilityBuilder/get_started.html', {"form": form})


def user_is_staff(user):
    return user.is_staff


@login_required
def dashboard(request):
    return render(request, 'durabilityBuilder/dashboard.html')


@login_required
def intro_day1(request):
    return render(request, 'durabilityBuilder/intro_day1.html')


@login_required
def intro_day2(request):
    return render(request, 'durabilityBuilder/intro_day2.html')


@login_required
def intro_day3(request):
    return render(request, 'durabilityBuilder/intro_day3.html')


@login_required
def intro_day4(request):
    return render(request, 'durabilityBuilder/intro_day4.html')


@login_required
def intro_day5(request):
    return render(request, 'durabilityBuilder/intro_day5.html')


@login_required
def intro_day6(request):
    return render(request, 'durabilityBuilder/intro_day6.html')


@login_required
def intro_day7(request):
    return render(request, 'durabilityBuilder/intro_day7.html')


@login_required
def intro_day8(request):
    return render(request, 'durabilityBuilder/intro_day8.html')


@login_required
def intro_day9(request):
    return render(request, 'durabilityBuilder/intro_day9.html')


@login_required
def intro_day10(request):
    return render(request, 'durabilityBuilder/intro_day10.html')


@login_required
def intro_day11(request):
    return render(request, 'durabilityBuilder/intro_day11.html')


@login_required
def intro_day12(request):
    return render(request, 'durabilityBuilder/intro_day12.html')


@login_required
def intro_day13(request):
    return render(request, 'durabilityBuilder/intro_day13.html')


@login_required
def intro_day14(request):
    return render(request, 'durabilityBuilder/intro_day14.html')

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Durability Builder</title>
    <meta content="" name="description">
    <meta content="" name="keywords">



    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
   <link rel="stylesheet" href="{% static 'css/style.css' %}">


{#    <link rel="stylesheet" href="{% static 'main.css' %}">#}
{#    <script defer src="{% static 'main.js' %}"></script>#}

    {% block headContent %}

    {% endblock %}

</head>
<body>

{#    <nav class="nav nav-top">#}
{#        <div class="logo-container">#}
{#            <a href="https://www.multisportenduranceacademy.com/"><img class="logo-img" src="{% static 'img/MEA-Logo1.png' %}" alt="MEA Logo"></a>#}
{#        </div>#}
{##}
{#        <ul class="nav-list">#}
{#            {% if user.is_authenticated %}#}
{#                <li><button href="#"><img class="menu-icon" src="{% static 'img/menu-icon.svg' %}" alt="Menu Icon"></button></li>#}
{#            {% else %}#}
{#                <li><button class="btn mea-btn" href="#">Login</button></li>#}
{#            {%  endif %}#}
{#        </ul>#}
{#    </nav>#}


  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top d-flex align-items-center">
    <div class="container d-flex align-items-center justify-content-between">

      <div class="logo">
        <a href="{% url 'durabilityBuilder:home' %}"><img class="img-fluid" src="{% static 'img/MEA-Logo1.png' %}" alt="MEA Logo"></a>
     </div>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto active" href="{% url 'durabilityBuilder:home' %}#hero">Home</a></li>
          <li><a class="nav-link scrollto" href="{% url 'durabilityBuilder:home' %}#about">About</a></li>
          <li><a class="nav-link scrollto" href="{% url 'durabilityBuilder:home' %}#services">Highlights</a></li>
          <li><a class="nav-link scrollto" href="{% url 'durabilityBuilder:home' %}#contact">Contact</a></li>
            {% if user.is_authenticated %}
                <li><a class="nav-link scrollto" href="{% url 'durabilityBuilder:dashboard' %}">Dashboard</a></li>
            {% else %}
                <li><a class="nav-link scrollto" href="{% url 'login' %}">Login</a></li>
            {%  endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->



    <div class="page-content">

{% block content %}

{% endblock %}

    </div>

  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row justify-content-between">

          <div class="col-lg-4 col-md-8 footer-contact">
            <h3>Durability Builder Program</h3>
            <p>
                <strong>Email:</strong> <a href="mailto:Tim@MultisportEnduranceAcademy.com">Tim@MultisportEnduranceAcademy.com</a><br>
            </p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'durabilityBuilder:home' %}#hero">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'durabilityBuilder:home' %}#about">About</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'durabilityBuilder:home' %}#services">Highlights</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'durabilityBuilder:home' %}#contact">Contact</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="{% url 'durabilityBuilder:get_started' %}">Get Started</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Our Social Networks</h4>
              <p>Join or visit The Durable Triathlete Facebook group.</p>
            <div class="social-links mt-3">
{#              <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>#}
              <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
{#              <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>#}
{#              <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>#}
{#              <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>#}
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="container py-4">
      <div class="copyright">
        &copy; Copyright 2024 <strong><span>Multisport Endurance Academy</span></strong>. All Rights Reserved
      </div>

    </div>
  </footer><!-- End Footer -->



  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>


</body>
</html>

templates/base_dashboard.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Durability Builder</title>
    <meta content="" name="description">
    <meta content="" name="keywords">



    <!-- Favicons -->
    <link href="{% static 'img/favicon.png' %}" rel="icon">
    <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="{% static 'vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
   <link rel="stylesheet" href="{% static 'css/style.css' %}">


    {% block headContent %}

    {% endblock %}

</head>
<body>


  <!-- ======= Header ======= -->
  <header id="header_nonav" class="fixed-top d-flex align-items-center">

    <div class="logo d-flex align-items-center justify-content-between ms-5">
        <a href="{% url 'durabilityBuilder:home' %}" class="logo d-flex align-items-center w-auto">
                          <img src="{% static 'img/MEADB_logo.png' %}" alt="">
{#          <h1 class="d-lg-block">Durability Builder</h1>#}
        </a>
       <i class="bi bi-list toggle-sidebar-btn ms-3"></i>
    </div><!-- End Logo -->

  </header><!-- End Header -->

  <!-- ======= Sidebar ======= -->
  <aside id="sidebar" class="sidebar">

    <ul class="sidebar-nav" id="sidebar-nav">

{#      <li class="nav-item">#}
{#        <a class="nav-link " href="{% url 'durabilityBuilder:dashboard' %}">#}
{#          <i class="bi bi-grid"></i>#}
{#          <span>Dashboard</span>#}
{#        </a>#}
{#      </li><!-- End Dashboard Nav -->#}

      <li class="nav-heading">2-Week Intro Program</li>

      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#week1-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Week1</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="week1-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'durabilityBuilder:intro_day1' %}">
              <i class="bi bi-circle"></i><span>Day 1</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day2' %}">
              <i class="bi bi-circle"></i><span>Day 2</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day3' %}">
              <i class="bi bi-circle"></i><span>Day 3</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day4' %}">
              <i class="bi bi-circle"></i><span>Day 4</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day5' %}">
              <i class="bi bi-circle"></i><span>Day 5</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day6' %}">
              <i class="bi bi-circle"></i><span>Day 6</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day7' %}">
              <i class="bi bi-circle"></i><span>Day 7</span>
            </a>
          </li>
        </ul>
      </li><!-- End Week 1 Nav -->


      <li class="nav-item">
        <a class="nav-link collapsed" data-bs-target="#week2-nav" data-bs-toggle="collapse" href="#">
          <i class="bi bi-menu-button-wide"></i><span>Week2</span><i class="bi bi-chevron-down ms-auto"></i>
        </a>
        <ul id="week2-nav" class="nav-content collapse " data-bs-parent="#sidebar-nav">
          <li>
            <a href="{% url 'durabilityBuilder:intro_day8' %}">
              <i class="bi bi-circle"></i><span>Day 8</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day9' %}">
              <i class="bi bi-circle"></i><span>Day 9</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day10' %}">
              <i class="bi bi-circle"></i><span>Day 10</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day11' %}">
              <i class="bi bi-circle"></i><span>Day 11</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day12' %}">
              <i class="bi bi-circle"></i><span>Day 12</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day13' %}">
              <i class="bi bi-circle"></i><span>Day 13</span>
            </a>
          </li>
          <li>
            <a href="{% url 'durabilityBuilder:intro_day14' %}">
              <i class="bi bi-circle"></i><span>Day 14</span>
            </a>
          </li>
        </ul>
      </li><!-- End Week 2 Nav -->

      <li class="nav-heading">My Account</li>

{% comment %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'durabilityBuilder:under_construction' %}">
          <i class="bi bi-person"></i>
          <span>Profile</span>
        </a>
      </li><!-- End Profile Page Nav -->
{% endcomment %}


      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'logout' %}">
          <i class="bi bi-box-arrow-right"></i>
          <span>Logout</span>
        </a>
      </li><!-- End Logout Page Nav -->


    </ul>

  </aside><!-- End Sidebar-->


{% block content %}

{% endblock %}



  <!-- Vendor JS Files -->
  <script src="{% static 'vendor/aos/aos.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'vendor/swiper/swiper-bundle.min.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'js/main.js' %}"></script>


</body>
</html>

templates/durabilityBuilder/dashboard.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Dashboard</h1>
            {% comment %}
      <nav>
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><a href="{% url 'durabilityBuilder:home' %}">Home</a></li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </nav>
{% endcomment %}
        </div><!-- End Page Title -->

        <section id="temp_dashboard" class="section workout-section">
            <div class="mt-5">
                <div class="vimeo-container">
                    <iframe src="https://player.vimeo.com/video/1113093937?h=b2f6763950&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                            frameborder="0"
                            allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share"
                            referrerpolicy="strict-origin-when-cross-origin"
                            title="DB Welcome, Home page"></iframe>
                </div>
                <script src="https://player.vimeo.com/api/player.js"></script>
            </div>

            <div class="section-title">What is the Durability Builder?</div>

            <p>Conversations in endurance sports, more often than not, circle back to the same thing: stiffness,
                strains, and injuries. I’ve been there, and chances are, you have too.</p>

            <p>That’s why I built the Durability Builder.</p>

            <p>It’s an online multisport training platform designed to take triathletes from <span class="bold-text">injury-prone and frustrated to durable, confident triathletes, through technique, mobility, and smart training that lasts.</span>
            </p>

            <p>It’s not about stacking endless miles. It’s about pairing your swim, bike, and run with the work that
                keeps you moving well, recovering faster, and training consistently.</p>

            <p>That’s how you stop breaking down and start breaking through.</p>

            <p>And you won’t be doing it alone. When you start, you’ll also get access to the <span class="bold-text">Durable Triathlete
                community.</span></p>

            <p>So welcome!</p>

            <p>You’re in the right place to start training like a Durable Triathlete.</p>

            <p>Click on <a href="{% url 'durabilityBuilder:intro_day1' %}">
                Day 1
            </a> to begin your 14-Day Durability Kickstart.</p>

            <p>I’ll see you inside.</p>

            <p><span class="list-title">Tim</span></p>

        </section>

    </main>




{% endblock %}

templates/durabilityBuilder/intro_day10.html
{% extends 'base_dashboard.html' %}

{% load static %}

{% block content %}

    <main id="main" class="main">

        <div class="pagetitle">
            <h1>Welcome to Day 10</h1>
            <hr/>
            <nav>
                <ol class="breadcrumb">
                    {#          <li class="breadcrumb-item"><a href="{% url 'durabilityBuilder:home' %}">Home</a></li>#}
                    <li class="breadcrumb-item"><a href="{% url 'durabilityBuilder:dashboard' %}">Dashboard</a></li>
                    <li class="breadcrumb-item active">Day 10</li>
                </ol>
            </nav>
        </div><!-- End Page Title -->

        <section id="intro-section" class="section workout-section">

            <div class="vimeo-container">
                <iframe src="https://player.vimeo.com/video/1102322842?h=aacff7ed29&amp;title=0&amp;byline=0&amp;portrait=0&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                        frameborder="0"
                        allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share"
                        referrerpolicy="strict-origin-when-cross-origin"
                        title="14 Day Durability Kickstart, Day 10"></iframe>
            </div>
            <script src="https://player.vimeo.com/api/player.js"></script>

            <div class="section-title">She finished pain-free (and you can too)</div>

            <p>Hey Athletes,</p>

            <p>Ever wonder what it would feel like to train without second-guessing every ache or worrying if you’re on
                the edge of another setback? That’s the real win athletes in this program talk about
                most—confidence.</p>

            <p>Now, let’s address the big question:<br/>Is the 6-Week Durability Builder (or customized monthly
                coaching) really worth it?</p>

            <p>If you’re already injury-free, moving well, and hitting your goals—awesome. Keep doing what works.</p>

            <p>But if you’re stuck in that cycle of training hard, getting hurt, starting over… or if nagging pain keeps
                stealing your progress, then yes—it’s worth it.</p>

            <p>Here’s why:<br/>Having someone review your numbers, provide feedback, and offer an objective point of
                view takes the second-guessing out of training. Even coaches need coaches. When someone else is guiding
                the plan, it frees up your mental energy to focus on doing the work—not questioning if you’re doing it
                right.</p>

            <p>One of my athletes told me her biggest win wasn’t a podium spot. It was waking up pain-free, lacing up
                her shoes, and actually looking forward to her runs again. That’s what we build in the Durability
                Builder Programs: confidence, efficiency, and a body that holds up—race after race, season after
                season.</p>

            <p>Watch today’s video where I reveal the hidden benefits.</p>

            <p>Then, check out today’s mobility and technique drills, do the exercises, and post your results or
                questions in the Facebook group for feedback.</p>

            <div class="section-subtitle">Today’s Mobility and Technique Challenge:</div>

            <p>Your shoulders might not scream during training, but they’re quietly stealing your swim speed. This
                shoulder mobilizer fixes that. And the jump rope drill? If done right, it develops all the muscles for a
                super efficient run form.</p>

            <ul>
                <li><span class="list-title">Daily Mobility</span>: Inverted Snow Angel</li>
                <li>
                    <div class="vimeo-container">
                        <iframe src="https://player.vimeo.com/video/1102353870?h=4e5e4a4ea2&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                                frameborder="0"
                                allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share"
                                referrerpolicy="strict-origin-when-cross-origin"
                                title="Inverted Snow Angel.mp4"></iframe>
                    </div>
                    <script src="https://player.vimeo.com/api/player.js"></script>
                </li>
                <li><span class="list-title">Technique Drill</span>: Jump Rope (tight glutes)</li>
                <li>
                    <div class="vimeo-container">
                        <iframe src="https://player.vimeo.com/video/1102360690?h=b284a3f69c&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479"
                                frameborder="0"
                                allow="autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share"
                                referrerpolicy="strict-origin-when-cross-origin"
                                title="jumprope.mp4"></iframe>
                    </div>
                    <script src="https://player.vimeo.com/api/player.js"></script>
                </li>
            </ul>

            <p>Did the drills? Sweet. Share a quick clip or results in the <a
                    href="https://www.facebook.com/groups/859964805679977" target="_blank">Facebook group</a> for some
                feedback.</p>

            <p>If you’re ready to take this beyond the 14-Day Kickstart, book a free 15-minute consultation, and we’ll
                map out your next steps together.</p>

            <p>Start where you are. Use what you have. Do what you can.</p>

            <p>See you tomorrow,</p>

            <p><span class="list-title">Tim</span></p>

            <p>P.S. Even coaches need coaches. Let’s take the guesswork out of your training—<a
                    href="https://api.leadconnectorhq.com/widget/booking/FogfFLBrYDZCw6JnmoGy" target="_blank">[schedule
                your free call here]</a>.</p>

            <p>P.P.S. Tomorrow, I’ll show you how to fit this all into even the busiest schedule without burning
                out.</p>

        </section>

    </main>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            // Get the collapse element
            const week1Nav = document.getElementById('week2-nav');
            // Create a Bootstrap collapse instance
            const bsCollapse = new bootstrap.Collapse(week1Nav, {
                toggle: false // Prevent automatic toggling
            });
            // Show the collapse
            bsCollapse.show();
        });
    </script>



{% endblock %}

templates/durabilityBuilder/under_construction.html
{% extends 'base.html' %}


{% load static %}


{% block headContent %}


{% endblock %}



{% block content %}

    <main class="page-content">
        <div class="container">
            <div class="row mt-3">
                <div class="text-center">
                    <img class="col-10" src="{% static 'img/under_construction.jpg' %}" alt="image not found">
                </div>
            </div>
        </div>
    </main>




{% endblock %}